export const ADD_ATTENDEES = "ADD_ATTENDEES";
export const REMOVE_ATTENDEES = "REMOVE_ATTENDEES";
export const GET_ATTENDEES = "GET_ATTENDEES";
export const UPDATE_ATTENDEES = "UPDATE_ATTENDEES";
export const CLEAR_ATTENDEES = "CLEAR_ATTENDEES";

export const EVENT_REGISTRATION_REQUEST = "EVENT_REGISTRATION_REQUEST";
export const EVENT_REGISTRATION_SUCCESS = "EVENT_REGISTRATION_SUCCESS";
export const EVENT_REGISTRATION_FAILURE = "EVENT_REGISTRATION_FAILURE";