export const MY_EVENT_CATEGORY_LIST_REQUEST = "MY_EVENT_CATEGORY_LIST_REQUEST";
export const MY_EVENT_CATEGORY_LIST_SUCCESS = "MY_EVENT_CATEGORY_LIST_SUCCESS";
export const MY_EVENT_CATEGORY_LIST_FAILURE = "MY_EVENT_CATEGORY_LIST_FAILURE";