export const EVENT_CATEGORY_LIST_REQUEST = "EVENT_CATEGORY_LIST_REQUEST";
export const EVENT_CATEGORY_LIST_SUCCESS = "EVENT_CATEGORY_LIST_SUCCESS";
export const EVENT_CATEGORY_LIST_FAILURE = "EVENT_CATEGORY_LIST_FAILURE";

export const EVENTS_BY_CATEGORY_LIST_REQUEST = "EVENTS_BY_CATEGORY_LIST_REQUEST";
export const EVENTS_BY_CATEGORY_LIST_SUCCESS = "EVENTS_BY_CATEGORY_LIST_SUCCESS";
export const EVENTS_BY_CATEGORY_LIST_FAILURE = "EVENTS_BY_CATEGORY_LIST_FAILURE";